### ISSUE TITLE
Fails to parse a file

### ISSUE THREAD

**Issue by vi** [icefoxen/cargo-osha#5]
```
$ RUST_BACKTRACE=1 LD_LIBRARY_PATH=~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib cargo-osha src/ws_client_peer.rs
Processing file src/ws_client_peer.rs
thread 'main' panicked at 'Unable to parse file: ParseError(Some("failed to parse crate: failed to parse all tokens"))', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: rust_begin_unwind
             at libstd/panicking.rs:328
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::result::unwrap_failed
   9: cargo_osha::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

The file is https://github.com/vi/websocat/blob/master/src/ws_client_peer.rs

**Comment by icefoxen** [comment]
The version of `syn` used for `cargo-osha` is currently out of date.  Updating it might fix this.

**Comment by anderejd** [comment]
I can confirm that my similar issues got resolved by updating syn.
